package com.example.common_ui.theme

import androidx.compose.ui.graphics.Color


internal val LightPrimary = Color(0xFF005CBC)
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFD7E2FF)
internal val LightOnPrimaryContainer = Color(0xFF001B3F)
internal val LightInversePrimary = Color(0xFFABC7FF)
internal val LightSecondary = Color(0xFF565E71)
internal val LightOnSecondary = Color(0xFFFFFFFF)
internal val LightSecondaryContainer = Color(0xFFDAE2F9)
internal val LightOnSecondaryContainer = Color(0xFF131C2C)
internal val LightTertiary = Color(0xFF9B442B)
internal val LightOnTertiary = Color(0xFFFFFFFF)
internal val LightTertiaryContainer = Color(0xFFFFDBD1)
internal val LightOnTertiaryContainer = Color(0xFF3B0900)
internal val LightBackground = Color(0xFFF8F8F8)
internal val LightOnBackground = Color(0xFF1A1B1F)
internal val LightSurface = Color(0xFFFFFFFF)
internal val LightOnSurface = Color(0xFF1A1B1F)
internal val LightSurfaceVariant = Color(0xFFE0E2EC)
internal val LightOnSurfaceVariant = Color(0xFFCBC9C9)
internal val LightSurfaceTint = Color(0xFF005CBC)
internal val LightInverseSurface = Color(0xFF2F3033)
internal val LightInverseOnSurface = Color(0xFFF2F0F4)
internal val LightError = Color(0xFFD0514B)
internal val LightOnError = Color(0xFFFFFFFF)
internal val LightErrorContainer = Color(0xFFFFDAD6)
internal val LightOnErrorContainer = Color(0xFF410002)
internal val LightOutline = Color(0xFFA9ABB4)
internal val LightOutlineVariant = Color(0xFFE0E2EC)
internal val LightScrim = Color(0xFF000000)

internal val DarkPrimary = Color(0xFFABC7FF)
internal val DarkOnPrimary = Color(0xFF002F66)
internal val DarkPrimaryContainer = Color(0xFF004590)
internal val DarkOnPrimaryContainer = Color(0xFFD7E2FF)
internal val DarkInversePrimary = Color(0xFF005CBC)
internal val DarkSecondary = Color(0xFFBEC6DC)
internal val DarkOnSecondary = Color(0xFF283041)
internal val DarkSecondaryContainer = Color(0xFF3E4759)
internal val DarkOnSecondaryContainer = Color(0xFFDAE2F9)
internal val DarkTertiary = Color(0xFFFFB5A0)
internal val DarkOnTertiary = Color(0xFF5E1703)
internal val DarkTertiaryContainer = Color(0xFF7C2D16)
internal val DarkOnTertiaryContainer = Color(0xFFFFDBD1)
internal val DarkBackground = Color(0xFF141B29)
internal val DarkOnBackground = Color(0xFFE3E2E6)
internal val DarkSurface = Color(0xFF1E2533)
internal val DarkOnSurface = Color(0xFFE3E2E6)
internal val DarkSurfaceVariant = Color(0xFF44474E)
internal val DarkOnSurfaceVariant = Color(0xFFCBC9C9)
internal val DarkSurfaceTint = Color(0xFFABC7FF)
internal val DarkInverseSurface = Color(0xFFE3E2E6)
internal val DarkInverseOnSurface = Color(0xFF2F3033)
internal val DarkError = Color(0xFFD0514B)
internal val DarkOnError = Color(0xFFFFFFFF)
internal val DarkErrorContainer = Color(0xFF93000A)
internal val DarkOnErrorContainer = Color(0xFFFFDAD6)
internal val DarkOutline = Color(0xFF8E9099)
internal val DarkOutlineVariant = Color(0xFF44474E)
internal val DarkScrim = Color(0xFF000000)